### ISSUE TITLE
No container to killdependency failed to start: container genai-stack-database-1 exited (1)

### ISSUE THREAD

**Issue by sidagarwal04** [docker/genai-stack#109]
[+] Running 2/0
 ✔ Container genai-stack-database-1    Created                             0.0s 
 ✔ Container genai-stack-pull-model-1  Created                             0.0s 
Attaching to api-1, bot-1, database-1, front-end-1, loader-1, pdf_bot-1, pull-model-1
pull-model-1  | pulling ollama model llama2 using http://host.docker.internal:11434
database-1    | Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
database-1    | Applying default values for plugin apoc to neo4j.conf
database-1    | Skipping dbms.security.procedures.unrestricted for plugin apoc because it is already set.
database-1    | You may need to add apoc.* to the dbms.security.procedures.unrestricted setting in your configuration file.
pulling manifest 
pull-model-1  | pulling 8934d96d3f08... 100% ▕▏ 3.8 GB                         
pulling manifest 
pull-model-1  | pulling 8934d96d3f08... 100% ▕▏ 3.8 GB                         
pulling manifest 
pulling manifest 
pull-model-1  | pulling 8934d96d3f08... 100% ▕▏ 3.8 GB                         
pull-model-1  | pulling 8c17c2ebb0ea... 100% ▕▏ 7.0 KB                         
pull-model-1  | pulling 7c23fb36d801... 100% ▕▏ 4.8 KB                         
pull-model-1  | pulling 2e0493f67d0c... 100% ▕▏   59 B                         
pull-model-1  | pulling fa304d675061... 100% ▕▏   91 B                         
pull-model-1  | pulling 42ba7f8a01dd... 100% ▕▏  557 B                         
pull-model-1  | verifying sha256 digest 
pull-model-1  | writing manifest 
pull-model-1  | removing any unused layers 
pull-model-1  | success 
pull-model-1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
no container to killdependency failed to start: container genai-stack-database-1 exited (1)

Tried running `docker compose up` multiple times but it is failing to start genai-stack-database-1

**Comment by hstm** [comment]
Could fix that by adding NEO4J_dbms_security_procedures_unrestricted=apoc.* to the database environment in docker-compose.yml:

```
...
environment:
      - NEO4J_AUTH=${NEO4J_USERNAME-neo4j}/${NEO4J_PASSWORD-password}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
...
```

**Comment by sidagarwal04** [comment]
Thanks @hstm. This worked fine. Closing this issue.
