### ISSUE TITLE
Support local Ollama model created from Modelfile

### ISSUE THREAD

**Issue by denverdino** [docker/genai-stack#112]
As a developer, I can build some local Ollama model for testing. But it cannot be used by Genai Stack directly.

Currently pull_model.Dockerfile will invoke ollama pull command to pull a model from a registry.

```
        (process/shell {:env {"OLLAMA_HOST" url} :out :inherit :err :inherit} (format "./bin/ollama pull %s" llm))
```

I think the proper way is to pull model if the model does not exist locally. The change should be simple, e.g.

```
        (process/shell {:env {"OLLAMA_HOST" url} :out :inherit :err :inherit} (format "bash -c './bin/ollama show %s --modelfile > /dev/null || ./bin/ollama pull %s'" llm llm))
```

**Comment by slimslenderslacks** [comment]
Cool, I think this will work for most people.  It wouldn't pull new versions of the model as part of `compose up` but maybe that should be outside of `compose up` anyway.

**Comment by jexp** [comment]
@mchiang0610 what do you think? There is also a PR for this
