### ISSUE TITLE
pull-model Warning     

### ISSUE THREAD

**Issue by BLKADO** [docker/genai-stack#162]
**Error message:**
! pull-model Warning          pull access denied for genai-stack/pull-model, repository does not exist or may require 'docker login': denied: requested access to the resource is denied                                                                   19.4s 
error pulling image configuration: download failed after attempts=6: dialing production.cloudflare.docker.com:443 container via direct connection because static system has no HTTPS proxy: connecting to 185.45.7.185:443: dial tcp 185.45.7.185:443: connectex: 
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

This error appears in windows10!

**Comment by BLKADO** [comment]
![Uploading Snipaste_2024-06-11_03-16-16.png…]()

**Comment by joeshawfieldatayo** [comment]
Did you get a resolution?
