### ISSUE TITLE
Unable to pull or build the pull-model image

### ISSUE THREAD

**Issue by mdf-ido** [docker/genai-stack#17]
I am getting Service pull-model has neither an image nor a build context specified and trying to change the compose file context and even trying to build the image directly with docker build -f results in errors.

**Comment by mdf-ido** [comment]
It ended up being an indentation issue. Let me know if you need me to send you a PR

**Comment by oskarhane** [comment]
I can't reproduce it, what OS and Docker Desktop / Compose version are you on?
A PR @mdf-ido would be much appreciated.

**Comment by Desnoo** [comment]
@mdf-ido The issue happens on linux systems. The docker compose up command was wrong. I created a pull request with a fix.
Use `docker compose --profile linux up` to  run it.

**Comment by slimslenderslacks** [comment]
@mdf-ido does this merge fix the problem for you?

**Comment by mdf-ido** [comment]
Yes thank you
