### ISSUE TITLE
ValueError: Could not connect to Neo4j database.

### ISSUE THREAD

**Issue by Mikemansour** [docker/genai-stack#20]
ValueError: Could not connect to Neo4j database. Please ensure that the url is correct
Traceback:
File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
File "/app/bot.py", line 38, in <module>
    neo4j_graph = Neo4jGraph(url=url, username=username, password=password)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/langchain/graphs/neo4j_graph.py", line 54, in __init__
    raise ValueError(
    
    
    OPENAI_API_KEY="sk-*************"
OLLAMA_BASE_URL="http://localhost:11434"
NEO4J_URI="neo4j://localhost:7687"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="Fq3uHU@NeNy"
LLM="gpt-3.5"
EMBEDDING_MODEL="openai"

LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_TRACING_V2=false
LANGCHAIN_PROJECT=#your-project-name
LANGCHAIN_API_KEY=#your-api-key ls_...

Please help

**Comment by Mikemansour** [comment]
running bot.py

**Comment by zooninja** [comment]
Hello, please note that in my issue thread I was advised with this 

https://github.com/docker/genai-stack/issues/18#issuecomment-1750407490 

and a Pull request was made to change the .env-example file in accordance to the above.
