### ISSUE TITLE
What happens when you hit "Submit a ticket"

### ISSUE THREAD

**Issue by zooninja** [docker/genai-stack#25]
What's expected to happen when one has generated a ticket and hits "Submit to support team"button? 
Is there a way to configure what happens?

**Comment by oskarhane** [comment]
The feature is there to showcase the _generation_ of a ticket. Submitting does nothing.
Clone the repo and configure it to do what you like it to, the code is here to inspire and get you started :)

**Comment by zooninja** [comment]
perfect, much appreciated. I've been playing with the stack for a few days and it's really awesome. Thanks a lot. Cheers.
