### ISSUE TITLE
Unable to locate package software-properties-common

### ISSUE THREAD

**Issue by hesh44** [docker/genai-stack#26]
```
=> ERROR [genai-stack_loader 3/9] RUN apt-get update && apt-get install -y     build-essential     curl     software-properties-common     && rm -rf /var/lib/apt/lists/*       37.7s
------
 > [genai-stack_loader 3/9] RUN apt-get update && apt-get install -y     build-essential     curl     software-properties-common     && rm -rf /var/lib/apt/lists/*:
#0 30.55 Ign:1 http://deb.debian.org/debian bookworm InRelease
#0 30.55 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
#0 30.55 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
#0 31.55 Ign:1 http://deb.debian.org/debian bookworm InRelease
#0 31.55 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
#0 31.55 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
#0 33.55 Ign:1 http://deb.debian.org/debian bookworm InRelease
#0 33.55 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
#0 33.55 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
#0 37.56 Err:1 http://deb.debian.org/debian bookworm InRelease
#0 37.56   Could not connect to debian.map.fastlydns.net:80 (199.232.18.132), connection timed out Unable to connect to deb.debian.org:http:
#0 37.56 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
#0 37.56   Unable to connect to deb.debian.org:http:
#0 37.56 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
#0 37.56   Unable to connect to deb.debian.org:http:
#0 37.56 Reading package lists...
#0 37.57 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.18.132), connection timed out Unable to connect to deb.debian.org:http:
#0 37.57 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Unable to connect to deb.debian.org:http:
#0 37.57 W: Failed to fetch http://deb.debian.org/debian-security/dists/bookworm-security/InRelease  Unable to connect to deb.debian.org:http:
#0 37.57 W: Some index files failed to download. They have been ignored, or old ones used instead.
#0 37.58 Reading package lists...
#0 37.59 Building dependency tree...
#0 37.59 Reading state information...
#0 37.59 Package build-essential is not available, but is referred to by another package.
#0 37.59 This may mean that the package is missing, has been obsoleted, or
#0 37.59 is only available from another source
#0 37.59 
#0 37.59 E: Package 'build-essential' has no installation candidate
#0 37.59 E: Unable to locate package software-properties-common
------
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y     build-essential     curl     software-properties-common     && rm -rf /var/lib/apt/lists/*]: exit code: 100
```

I am getting this error. What is the problem?

I tried to set proxy ENV at beginning of Dockerfile, but it didn't help.
I tried to run official ubuntu image and install tools from RUN command and it worked.

CentOS 7
Docker version 20.10.17, build 100c701
docker-compose version 1.18.0, build 8dd22a9

**Comment by zooninja** [comment]
> ```
> => ERROR [genai-stack_loader 3/9] RUN apt-get update && apt-get install -y     build-essential     curl     software-properties-common     && rm -rf /var/lib/apt/lists/*       37.7s
> ------
>  > [genai-stack_loader 3/9] RUN apt-get update && apt-get install -y     build-essential     curl     software-properties-common     && rm -rf /var/lib/apt/lists/*:
> #0 30.55 Ign:1 http://deb.debian.org/debian bookworm InRelease
> #0 30.55 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
> #0 30.55 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
> #0 31.55 Ign:1 http://deb.debian.org/debian bookworm InRelease
> #0 31.55 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
> #0 31.55 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
> #0 33.55 Ign:1 http://deb.debian.org/debian bookworm InRelease
> #0 33.55 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
> #0 33.55 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
> #0 37.56 Err:1 http://deb.debian.org/debian bookworm InRelease
> #0 37.56   Could not connect to debian.map.fastlydns.net:80 (199.232.18.132), connection timed out Unable to connect to deb.debian.org:http:
> #0 37.56 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
> #0 37.56   Unable to connect to deb.debian.org:http:
> #0 37.56 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
> #0 37.56   Unable to connect to deb.debian.org:http:
> #0 37.56 Reading package lists...
> #0 37.57 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.18.132), connection timed out Unable to connect to deb.debian.org:http:
> #0 37.57 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Unable to connect to deb.debian.org:http:
> #0 37.57 W: Failed to fetch http://deb.debian.org/debian-security/dists/bookworm-security/InRelease  Unable to connect to deb.debian.org:http:
> #0 37.57 W: Some index files failed to download. They have been ignored, or old ones used instead.
> #0 37.58 Reading package lists...
> #0 37.59 Building dependency tree...
> #0 37.59 Reading state information...
> #0 37.59 Package build-essential is not available, but is referred to by another package.
> #0 37.59 This may mean that the package is missing, has been obsoleted, or
> #0 37.59 is only available from another source
> #0 37.59 
> #0 37.59 E: Package 'build-essential' has no installation candidate
> #0 37.59 E: Unable to locate package software-properties-common
> ------
> failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y     build-essential     curl     software-properties-common     && rm -rf /var/lib/apt/lists/*]: exit code: 100
> ```
> 
> I am getting this error. What is the problem?
> 
> I tried to set proxy ENV at beginning of Dockerfile, but it didn't help. I tried to run official ubuntu image and install tools from RUN command and it worked.
> 
> CentOS 7 Docker version 20.10.17, build 100c701 docker-compose version 1.18.0, build 8dd22a9

Hello this is a package repository issue and is not related to the genai stack. 
update and cleaning of the package cache should solve it.

**Comment by jexp** [comment]
Did that help @hesh44 ?

**Comment by hesh44** [comment]
Yes it did. I ran `apt-get update && apt-get clean && apt-get install -y build-essential \` and it worked. Thank you @zooninja

**Comment by cesarvspr** [comment]
The fix above didn't work for me, unfortunately.

**Comment by andysacko** [comment]
it worked for me but what i did was comment out everything in the /etc/sources.list the run apt-get update && apt-get clean && apt-get install -y build-essential

**Comment by caelum-artifex** [comment]
Hello, everyone
```
sudo add-apt-repository universe
```
Pls check
https://askubuntu.com/questions/148638/how-do-i-enable-the-universe-repository

It worked for me.
