### ISSUE TITLE
GPU support may not be enabled

### ISSUE THREAD

**Issue by svanschalkwyk** [docker/genai-stack#62]
"routes.go:634: Warning: GPU support may not enabled, check you have installed install GPU drivers: nvidia-smi command failed"
 NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2  
5.15.0-86-generic #96-Ubuntu
docker run --rm  --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi:
NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2

**Comment by svanschalkwyk** [comment]
llama.go:333: skipping accelerated runner because num_gpu=0
genai-stack-llm-1         | 2023/10/21 03:52:30 llama.go:356: starting llama runner
genai-stack-llm-1         | 2023/10/21 03:52:30 llama.go:408: waiting for llama runner to start responding
genai-stack-llm-1         | [GIN] 2023/10/21 - 03:52:30 | 500 |  873.831145ms |      172.20.0.5 | POST     "/api/generate"
genai-stack-llm-1         | 2023/10/21 03:52:30 llama.go:373: error starting llama runner: llama runner process has terminated
genai-stack-llm-1         | 2023/10/21 03:52:30 llama.go:438: llama runner stopped with error: signal: illegal instruction (core dumped)

**Comment by jexp** [comment]
Is that on linux? Can you share more of your OS and machine specs. 
@mchiang0610

**Comment by matthieuml** [comment]
If you are using the Linux profile, I believe you should add this to the `llm` service:
```
deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```
And ensure that you have `nvidia-container-toolkit` installed

**Comment by svanschalkwyk** [comment]
Thank you. That works.


Steph van Schalkwyk
Principal, remcam llc, dba. Remcam Search Engines
Elastic Partner
+1.314.452.2896
***@***.***
Skype: svanschalkwyk
<http://linkedin.com/in/vanschalkwyk>

**Comment by jexp** [comment]
Added it to the readme.
