### ISSUE TITLE
dependency failed to start: container genai-stack-database-1 is unhealthy

### ISSUE THREAD

**Issue by svanschalkwyk** [docker/genai-stack#63]
"genai-stack-pull-model-1 exited with code 0
dependency failed to start: container genai-stack-database-1 is unhealthy"

docker ps:
...:::7687->7687/tcp   genai-stack-database-1 --- so this is started
11434/tcp                   genai-stack-llm-1
Browser on port 7474:
"ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason is not available."
Seems that the neo4j password is not set from the .env file . 
Default password also not working.

**Comment by svanschalkwyk** [comment]
Further with lllama2:
"   File "/usr/local/lib/python3.11/site-packages/langchain/graphs/neo4j_graph.py", line 70, in __init__
genai-stack-api-1         |     raise ValueError(
genai-stack-api-1         | ValueError: Could not connect to Neo4j database. Please ensure that the username and password are correct"

**Comment by svanschalkwyk** [comment]
Follow up: Can start now. Tried llama2 and password was set. 
Still looking into it.

**Comment by jexp** [comment]
Ok. Please share the config and how it’s going

**Comment by oskarhane** [comment]
Try `docker compose down` and then `docker compose up` to remove the containers and get a fresh start.

**Comment by svanschalkwyk** [comment]
Re-run
docker compose --profile linux up
It will eventually start. Not sure if there might be a database check that needs to be extended. Will check later.

**Comment by jbonfardeci** [comment]
I was able to get it to work by running, `sudo docker compose down`
Then add the following argument --force-recreate: `docker compose --profile linux up --force-recreate`
