### ISSUE TITLE
service "pull-model" didn't complete successfully: exit 1

### ISSUE THREAD

**Issue by Ji-Shao** [docker/genai-stack#76]
docker compose up
-- omitted for brevity --
genai-stack-pull-model-1  | pulling ollama model llama2 using http://host.docker.internal:11434
genai-stack-pull-model-1  | Error: Head "http://host.docker.internal:11434/": dial tcp: lookup host.docker.internal on 127.0.0.11:53: no such host
genai-stack-pull-model-1 exited with code 1

**Comment by Ji-Shao** [comment]
I figured it out. 
1) .env file
LLM=llama2 
EMBEDDING_MODEL=sentence_transformer
OLLAMA_BASE_URL=http://llm:11434

2) docker compose --profile linux up

**Comment by hafiz031** [comment]
Changed to `http://llm:11434`  but still getting:
```
Attaching to api-1, bot-1, database-1, front-end-1, loader-1, pdf_bot-1, pull-model-1
pull-model-1  | pulling ollama model mistral using http://llm:11434
pull-model-1  | Error: Head "http://llm:11434/": dial tcp: lookup llm on 127.0.0.11:53: server misbehaving
pull-model-1  | Error: Head "http://llm:11434/": dial tcp: lookup llm on 127.0.0.11:53: server misbehaving
pull-model-1 exited with code 1
service "pull-model" didn't complete successfully: exit 1
```
