### ISSUE TITLE
Develop: tag change in last revision.

### ISSUE THREAD

**Issue by ladriskylepatrick** [docker/genai-stack#77]
OS Image : AWS : amazon/Deep Learning AMI GPU PyTorch 2.0.1 (Ubuntu 20.04) 20231003

Upon running docker compose up the following error happens in the command line:
Additional Property is not allowed Develop

I reverted back to the prior commit which had the develop lines as x-develop and the docker command compose up worked as intended on this image.

**Comment by oskarhane** [comment]
Thanks for reporting this, fixed in https://github.com/docker/genai-stack/commit/c3283349e6adbb03ec1b1a709b3362476b4aec39
