### ISSUE TITLE
Additional property develop is not allowed

### ISSUE THREAD

**Issue by Ji-Shao** [docker/genai-stack#78]
Ubuntu 22.04.3 LTS

genai-stack/docker-compose.yml: services.bot Additional property develop is not allowed

**Comment by matthieuml** [comment]
Same, the latest version in `apt` repositories for now is `Docker Compose version v2.21.0`.

I think we either need to wait for `v2.22.0` to come out, or build from source, or even keep x-develop for now.

**Comment by oskarhane** [comment]
Thanks for reporting this, fixed with https://github.com/docker/genai-stack/commit/c3283349e6adbb03ec1b1a709b3362476b4aec39
