### ISSUE TITLE
Error in building docker image

### ISSUE THREAD

**Issue by atharvabagde** [docker/genai-stack#92]
I am trying to run the docker compose up command after cloning the git repo, to build the docker container however I am facing following error:

=> ERROR [api 3/8] RUN apt-get update && apt-get install -y     build-es  0.5s

0.491 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
0.491   At least one invalid signature was encountered.
0.495 Reading package lists...
0.503 W: GPG error: http://deb.debian.org/debian bookworm InRelease: At least one invalid signature was encountered.
0.503 E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.

failed to solve: process "/bin/sh -c apt-get update && apt-get install -y     build-essential     curl     software-properties-common     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

Can someone help with this please

**Comment by dseven** [comment]
Don't know what this project is, but stumbled in here when I ran into the same symptom (attempting to build my own container image). Turns out that this happens a lot when the filesystem that docker is using for container overlays get full, but the error message is quite unhelpful. Check your filesystem space?

**Comment by atharvabagde** [comment]
Thanks for the response dseven! 
In my case actually, one of the layers was corrupted. Clearing the layer cache in docker and rebuilding helped me sort the problem out.

**Comment by kylebebak** [comment]
On MacOS I did `docker builder prune` to clear the build cache, and the issue above was resolved

**Comment by roopesh-bhat** [comment]
@kylebebak  Thnaks buddy its working

**Comment by jak4** [comment]
Spot on! Thanks for the comment!

**Comment by wochae** [comment]
thx!

**Comment by mattkomarnicki** [comment]
In my case I had to completely remove everything with `docker system prune`. This reclaimed 40 GB of data and all issues (that have occurred while building) were solved.

**Comment by hainguyenp207** [comment]
> `docker builder prune`

Thanks. It worked

**Comment by Yuanyuan-Shen** [comment]
In my case I deleted previous unused images, ran `docker builder prune -f`, and add `--no-cache` into the `docker build command`. It worked
